// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: enumeration.proto

package ProtoCourse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Eyecolor int32

const (
	Eyecolor_Eye_Color_Unspecified Eyecolor = 0
	Eyecolor_Eye_Color_Red         Eyecolor = 1
	Eyecolor_Eye_Color_Blue        Eyecolor = 2
	Eyecolor_Eye_Color_Green       Eyecolor = 3
)

// Enum value maps for Eyecolor.
var (
	Eyecolor_name = map[int32]string{
		0: "Eye_Color_Unspecified",
		1: "Eye_Color_Red",
		2: "Eye_Color_Blue",
		3: "Eye_Color_Green",
	}
	Eyecolor_value = map[string]int32{
		"Eye_Color_Unspecified": 0,
		"Eye_Color_Red":         1,
		"Eye_Color_Blue":        2,
		"Eye_Color_Green":       3,
	}
)

func (x Eyecolor) Enum() *Eyecolor {
	p := new(Eyecolor)
	*p = x
	return p
}

func (x Eyecolor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Eyecolor) Descriptor() protoreflect.EnumDescriptor {
	return file_enumeration_proto_enumTypes[0].Descriptor()
}

func (Eyecolor) Type() protoreflect.EnumType {
	return &file_enumeration_proto_enumTypes[0]
}

func (x Eyecolor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Eyecolor.Descriptor instead.
func (Eyecolor) EnumDescriptor() ([]byte, []int) {
	return file_enumeration_proto_rawDescGZIP(), []int{0}
}

type EnumrateEye struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EyeColor Eyecolor `protobuf:"varint,1,opt,name=eye_color,json=eyeColor,proto3,enum=example.enum.Eyecolor" json:"eye_color,omitempty"`
}

func (x *EnumrateEye) Reset() {
	*x = EnumrateEye{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enumeration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumrateEye) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumrateEye) ProtoMessage() {}

func (x *EnumrateEye) ProtoReflect() protoreflect.Message {
	mi := &file_enumeration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumrateEye.ProtoReflect.Descriptor instead.
func (*EnumrateEye) Descriptor() ([]byte, []int) {
	return file_enumeration_proto_rawDescGZIP(), []int{0}
}

func (x *EnumrateEye) GetEyeColor() Eyecolor {
	if x != nil {
		return x.EyeColor
	}
	return Eyecolor_Eye_Color_Unspecified
}

var File_enumeration_proto protoreflect.FileDescriptor

var file_enumeration_proto_rawDesc = []byte{
	0x0a, 0x11, 0x65, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x65, 0x6e, 0x75,
	0x6d, 0x22, 0x42, 0x0a, 0x0b, 0x45, 0x6e, 0x75, 0x6d, 0x72, 0x61, 0x74, 0x65, 0x45, 0x79, 0x65,
	0x12, 0x33, 0x0a, 0x09, 0x65, 0x79, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x45, 0x79, 0x65, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x08, 0x65, 0x79, 0x65,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x2a, 0x61, 0x0a, 0x08, 0x45, 0x79, 0x65, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x79, 0x65, 0x5f, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x55,
	0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d,
	0x45, 0x79, 0x65, 0x5f, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x52, 0x65, 0x64, 0x10, 0x01, 0x12,
	0x12, 0x0a, 0x0e, 0x45, 0x79, 0x65, 0x5f, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x42, 0x6c, 0x75,
	0x65, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x79, 0x65, 0x5f, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x5f, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x10, 0x03, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_enumeration_proto_rawDescOnce sync.Once
	file_enumeration_proto_rawDescData = file_enumeration_proto_rawDesc
)

func file_enumeration_proto_rawDescGZIP() []byte {
	file_enumeration_proto_rawDescOnce.Do(func() {
		file_enumeration_proto_rawDescData = protoimpl.X.CompressGZIP(file_enumeration_proto_rawDescData)
	})
	return file_enumeration_proto_rawDescData
}

var file_enumeration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enumeration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_enumeration_proto_goTypes = []interface{}{
	(Eyecolor)(0),       // 0: example.enum.Eyecolor
	(*EnumrateEye)(nil), // 1: example.enum.EnumrateEye
}
var file_enumeration_proto_depIdxs = []int32{
	0, // 0: example.enum.EnumrateEye.eye_color:type_name -> example.enum.Eyecolor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_enumeration_proto_init() }
func file_enumeration_proto_init() {
	if File_enumeration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enumeration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumrateEye); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enumeration_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enumeration_proto_goTypes,
		DependencyIndexes: file_enumeration_proto_depIdxs,
		EnumInfos:         file_enumeration_proto_enumTypes,
		MessageInfos:      file_enumeration_proto_msgTypes,
	}.Build()
	File_enumeration_proto = out.File
	file_enumeration_proto_rawDesc = nil
	file_enumeration_proto_goTypes = nil
	file_enumeration_proto_depIdxs = nil
}
